### ISSUE TITLE
/etc/profile.d/freetype-infinality.sh: source: not found

### ISSUE THREAD

**Issue by bwat47** [chenxiaolong/Debian-Packages#1]
Been having some trouble with this out of the blue. all the sudden infinality wasn't properly setting my xft settings on boot, and I noticed this in my xsession-errors:

/etc/gdm3/Xsession: Beginning session setup...
/etc/gdm3/Xsession: 1: /etc/profile.d/freetype-infinality.sh: source: not found
/etc/gdm3/Xsession: 5: /etc/profile.d/freetype-infinality.sh: [[: not found

I tried purging the packages, recompiling the, and reinstalling them. the file that source points to in freetype-infinality.sh does exist and is set to true so I don't understand why this is happening...

**Comment by chenxiaolong** [comment]
This looks exactly line what would happen if /etc/gdm3/Xsession is run with sh instead of bash. Could you upload your /etc/gdm3/Xsession file somewhere (like http://gist.github.com). Thanks!

**Comment by chenxiaolong** [comment]
The issue should be fixed with commit 275fcae377acbae6d21eb3c78be2f7f25b2d00e8 Please reopen this bug if it still does not work.

**Comment by bwat47** [comment]
Sorry for taking long to respond. still seems to be doing it, and this is on a totally clean (and updated) wheezy install.

I just compiled and installed the freetype packages fresh too. Here is what I now have in .xsession-errors (slightly different then before that commit)

/etc/gdm3/Xsession: Beginning session setup...
/etc/gdm3/Xsession: 7: /etc/profile.d/freetype-infinality.sh: [[: not found

and here is my gdm xsession file: https://gist.github.com/bwat47/6143877#file-xsession

**Comment by chenxiaolong** [comment]
No problem. Yeah, I missed one change I needed to make. The new commit (5faa542962f3bbdf16f4ab506abf01ef80458944) should work now.
